#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
export PATH=/usr/local/bin:$PATH
# open /Applications/SourceTree.app/Contents/MacOS/SourceTree

branch="$(git rev-parse --abbrev-ref HEAD)"

# npx lint-staged

node update-version.js 
