#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
export PATH=/usr/local/bin:$PATH
# open /Applications/SourceTree.app/Contents/MacOS/SourceTree

branch="$(git rev-parse --abbrev-ref HEAD)"
echo "Branch: $branch"

npx lint-staged
