name: Workflow Bump Version

on:
    pull_request:
        branches: [pre-production]
        types: [closed]

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: "Thai-bug/test-auto-increment.git"
          token: ${{ secrets.GIT_PASSWORD }} 
          ref: pre-production

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Update version
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          npm version patch
      
      - name: Commit and push
        run: |
          git push