name: Workflow Bump Version

on:
    pull_request:
        branches: [pre-production]

jobs:
    bump_version:
        name: Bump Version
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v2
        -   name: Bump Version
            id: bump_version
            run: |
                echo "test"
